### ISSUE TITLE
Connection refused on localhost (when selfhosting)

### ISSUE THREAD

**Issue by tarasis** [zachleat/speedlify#71]
I was trying to self host speedlify on a VPS I have rather than netlify.

When I run it on the VPS (x86_64), and also on my Rapsberry PI running Raspbian Bookworm I get the following error

```
VPS Results

rob@kvm-ams:~/speedlify$ npm run test-pages

> speedlify@1.0.0 test-pages
> node run-tests

There are no known last run timestamps
First tests for galshaw.
Testing 1 site:
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: connect ECONNREFUSED 127.0.0.1:39819
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 39819
}

Node.js v18.17.1
rob@kvm-ams:~/speedlify$ 

----

PI Results

tarasis@rp4b:~/git-repos/speedlify $ npm run test-pages

> speedlify@1.0.0 test-pages
> node run-tests

There are no known last run timestamps
First tests for galshaw.
Testing 1 site:
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: connect ECONNREFUSED 127.0.0.1:40835
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1602:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 40835
}

Node.js v21.6.1

```

However on my Mac* & Netlify it runs perfectly.

```
Last runs at start:  {}
First tests for galshaw.
Testing 1 site:
(Site 1 of 1, run 1 of 3): https://galshaw.it
(Site 1 of 1, run 2 of 3): https://galshaw.it
(Site 1 of 1, run 3 of 3): https://galshaw.it
Axe scan (1 of 1) for https://galshaw.it
Writing ./_data/results/e8b5024f/date-1706963769478.json.
Finished testing "galshaw".
Last runs after "galshaw": {"galshaw":{"timestamp":1706963790553}}
```

**Comment by Akashic101** [comment]
I am running into the same problem on my Pi3, the issue seems to be the same as #65. I am unsure how to fix this, the comments in that issue didn't really help as setting the path of chrome (or Firefox) using `executablePath: '/usr/bin/chrome-browser',` did not work. Whats also weird is that the port printed out from the error is always different. Did you found a solution to this problem in the end?

Note: Speedlify runs perfectly fine on my Win10-PC and my Ubuntu-server with no chances needed. Perhaps an issue with the Pi being ARM64 and not AMD64?

**Comment by marc-bouvier** [comment]
I have a similar issue running from Github Action.

https://github.com/baldir-fr/coda-speedlify

```
Run npm run test-pages
  npm run test-pages
  shell: /usr/bin/bash -e {0}

> speedlify@1.0.0 test-pages
> node run-tests

Last runs at start:  {}
First tests for coda-[2](https://github.com/baldir-fr/coda-speedlify/actions/runs/16145612937/job/45563524454#step:6:2)025-b1.
[performance-leaderboard] Testing 1 site:
[performance-leaderboard] Unhandled rejection in promise Error: connect ECONNREFUSED 127.0.0.1:[3](https://github.com/baldir-fr/coda-speedlify/actions/runs/16145612937/job/45563524454#step:6:3)8751
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1611:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 387[5](https://github.com/baldir-fr/coda-speedlify/actions/runs/16145612937/job/45563524454#step:6:6)1
}
```

**Comment by marc-bouvier** [comment]
Thanks to @ythirion (and some folk named Claude 😉), we managed to run the analysis inside an Ubuntu container in GitHub Actions.

One key points seems to be coming from [this Chromium documentation about AppArmor restrictions](https://chromium.googlesource.com/chromium/src/+/main/docs/security/apparmor-userns-restrictions.md).

@tarasis , @Akashic101, I am pretty confident you can adapt this for your self-hosted workflows.


## Tweaked `performance-leaderboard`

Yoan also had to adapt some code in the `performance-leaderboard` dependency (which he brought into the speedlify repository to ease tweaking).

It seems that the default chrome flags were hard-coded and could not be overriden properly later with options.

- https://github.com/zachleat/performance-leaderboard/issues/24

Changes made to `performance-leaderboard/performance-leaderboard.js`


```diff
@@ -19,6 +19,16 @@
     const chromeLauncher = await import("chrome-launcher");
     const {default: lighthouse} = await import("lighthouse");
 
+    const defaultChromeFlags = [
+        '--no-sandbox',
+        '--disable-setuid-sandbox',
+        '--disable-dev-shm-usage',
+        '--disable-gpu',
+        '--headless=new',
+        '--ignore-certificate-errors',
+        '--no-enable-error-reporting',
+    ];
+
     let opts = Object.assign({
         writeLogs: true,
         logDirectory: LOG_DIRECTORY,
@@ -26,12 +36,7 @@
         axePuppeteerTimeout: AXE_PUPPETEER_TIMEOUT,
         bypassAxe: [], // skip axe checks
         // onlyCategories: ["performance", "accessibility"],
-        chromeFlags: [
-            '--headless',
-            '--disable-dev-shm-usage',
-            '--ignore-certificate-errors',
-            '--no-enable-error-reporting',
-        ],
+        chromeFlags: defaultChromeFlags,
         freshChrome: "site", // or "run"
         launchOptions: {},
         // callback before each lighthouse test
@@ -45,6 +50,15 @@
         }, // async compatible
     }, options);
 
+    // Ensure default Chrome flags are always included, even if options overrides chromeFlags
+    if (options && options.chromeFlags) {
+        opts.chromeFlags = [...defaultChromeFlags, ...options.chromeFlags];
+    } else {
+        opts.chromeFlags = defaultChromeFlags;
+    }
+
+    log(`Chrome flags: ${opts.chromeFlags.join(' ')}`);
+
     let config = null;
 
     let resultLog = new ResultLogger();
@@ -64,22 +78,32 @@
         let portNumber;
 
         if (!opts.readFromLogDirectory && opts.freshChrome === "run") {
-            chrome = await chromeLauncher.launch(Object.assign({
+            const launcherConfig = {
+                chromePath: opts.launchOptions.chromePath || chromePuppeteerPath,
                 chromeFlags: opts.chromeFlags,
-                // reuse puppeteer chrome path
-                chromePath: chromePuppeteerPath,
-            }, opts.launchOptions));
+                ignoreDefaultFlags: false,
+                ...opts.launchOptions
+            };
+            // Ensure chromeFlags aren't overridden by launchOptions
+            launcherConfig.chromeFlags = opts.chromeFlags;
 
+            log(`Launching chrome with config: ${JSON.stringify(launcherConfig, null, 2)}`);
+            chrome = await chromeLauncher.launch(launcherConfig);
             portNumber = chrome.port;
         }
         for (let url of urls) {
             if (!opts.readFromLogDirectory && opts.freshChrome === "site") {
-                chrome = await chromeLauncher.launch(Object.assign({
+                const launcherConfig = {
+                    chromePath: opts.launchOptions.chromePath || chromePuppeteerPath,
                     chromeFlags: opts.chromeFlags,
-                    // reuse puppeteer chrome path
-                    chromePath: chromePuppeteerPath,
-                }, opts.launchOptions));
+                    ignoreDefaultFlags: false,
+                    ...opts.launchOptions
+                };
+                // Ensure chromeFlags aren't overridden by launchOptions
+                launcherConfig.chromeFlags = opts.chromeFlags;
 
+                log(`Launching chrome with config: ${JSON.stringify(launcherConfig, null, 2)}`);
+                chrome = await chromeLauncher.launch(launcherConfig);
                 portNumber = chrome.port;
             }

```


## Modified `run-tests.js`

Temporarily modified  `run-tests.js` to use local `performance-leaderboard` tweaks until it is patched.

```diff
@@ -2,7 +2,10 @@
 const fs = require("fs").promises;
 const shortHash = require("short-hash");
 const fastglob = require("fast-glob");
-const PerfLeaderboard = require("performance-leaderboard");
+const PerfLeaderboard = require("./lib/performance-leaderboard/performance-leaderboard.js");
+
+const chromePath = process.env.CHROME_PATH || require("puppeteer").executablePath();
+console.info(`Using Chromium at: ${chromePath}`);
 
 const NUMBER_OF_RUNS = 3;
 const FREQUENCY = 60; // in minutes
@@ -105,8 +108,12 @@
 
         let runCount =
             group.options && group.options.runs ? group.options.runs : NUMBER_OF_RUNS;
+
         let options = Object.assign({
-            chromeFlags: ['--headless', '--disable-dev-shm-usage']
+            launchOptions: {
+                chromePath: chromePath,
+                logLevel: 'verbose'
+            }
         }, group.options);
 
         let results = await PerfLeaderboard(

```


## Added an endpoint bash script to deploy scheduled

```sh
#!/bin/bash  
echo "Scan and publish Speedlify"  
cd "$(dirname "$0")/.." || exit 1  
git reset --hard  
npm run test-pages  
git add .  
git commit -m "Automatic Scan and publish $(date)"  
git push --force
```


## GitHub Action Workflows

See an example of Github Actions here : 

https://github.com/baldir-fr/template-speedlify-gh-actions/tree/live/.github/workflows

```yml
name: Speedlify — scan & publish

on:
  schedule:
    # The action is triggered periodically “At 20:00 on Monday.” (https://crontab.guru/#0_20_*_*_1)
    - cron: "0 20 * * 1"
  # Allows the action to be triggered manually from GitHub "Actions" tab
  workflow_dispatch: { }

permissions:
  contents: write
  # Allows other GH actions to be triggered when this one finishes
  actions: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install npm dependencies
        run: npm install

      - name: Install chrome
        uses: browser-actions/setup-chrome@v2
        id: setup-chrome

      # https://chromium.googlesource.com/chromium/src/+/main/docs/security/apparmor-userns-restrictions.md
      - name: Disable AppArmor user namespace restrictions
        run: echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns

      - name: Git identity for CI
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Make script executable
        run: chmod +x scripts/run-publish.sh

      - name: Run publish script
        env:
          CHROME_PATH: ${{ steps.setup-chrome.outputs.chrome-path }}
          CHROME_DEVEL_SANDBOX: /usr/local/sbin/chrome-devel-sandbox
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
        run: |
          cd scripts
          ./run-publish.sh
```

Deployment is pretty straightforward (in another GH workflow).
```yml
name: Deploy Pages

on:
  push:
    branches: ["live"]
  # Allows the action to be triggered manually from Github "Actions" tab
  workflow_dispatch:
  workflow_run:
    # This action is triggered when the "Speedlify — scan & publish" is completed
    workflows: ["Speedlify — scan & publish"]
    types: 
      - "completed"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Install npm dependencies
        run: npm install
      - name: Build speedlify
        run: |
          npm run build -- --pathprefix=${GITHUB_REPOSITORY#*/}
          npm run zip-results
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

```
